name: CI Pipeline

on:
  pull_request:
    branches:
      - feature/soma
      - feature/subtracao
      - feature/divisao
      - feature/multiplicacao
  push:
    branches:
      - develop
      - homolog
      - main

jobs:
  # Job para rodar os testes na branch 'develop'
  test-develop:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Aqui você roda seus testes
          pytest

      - name: Merge to develop
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout develop
          git merge feature/soma
          git push origin develop
        if: success() # Só realiza o merge se os testes passarem

  # Job para rodar os testes na branch 'homolog' após o merge com 'develop'
  test-homolog:
    runs-on: ubuntu-latest
    needs: test-develop
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Merge to homolog
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout homolog
          git merge develop
          git push origin homolog
        if: success()

  # Job para rodar os testes na branch 'main' após o merge com 'homolog'
  test-main:
    runs-on: ubuntu-latest
    needs: test-homolog
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Merge to main
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout main
          git merge homolog
          git push origin main
        if: success()
